apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-formation
  namespace: paris-user-ns
spec:
  hard:
    requests.cpu: "900m"       # Max 900 millicores en requests
    requests.memory: "512Mi"   # Max 512 Mi en requests
    limits.cpu: "2"            # Max 2 CPU en limits
    limits.memory: "1Gi"       # Max 1 Gi en limits
    pods: "5"                  # Max 5 pods
