apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cronjob-console
  namespace: exercice-nginx
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob
              image: registry.access.redhat.com/ubi8/nginx-120
              command: ["/bin/sh", "-c", "echo CronJob OpenShift fonctionne"]
          restartPolicy: Never