apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job-console
  namespace: exercice-nginx
spec:
  template:
    spec:
      containers:
        - name: job
          image: busybox
          command: ["echo", "Bonjour depuis mon Job OpenShift"]
      restartPolicy: Never