apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: formation-openshift
resources:
  - configmap-nginx-dashboard.yaml
  - configmap-nginx-conf.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml