apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cronjob-console
  namespace: exercice-nginx-3
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob
              image: busybox
              command: ["echo", "CronJob OpenShift fonctionne"]
          restartPolicy: Never
